name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Set up uv
        uses: astral-sh/setup-uv@v5

      - name: Install GSL
        run: sudo apt-get update && sudo apt-get install -y libgsl-dev

      - name: Install dependencies
        run: |
          uv pip install -e ".[dev,science]"

      - name: Run Ruff (lint and syntax)
        run: |
          uv run ruff check galform_analysis

      - name: Run tests
        run: |
          uv run pytest tests

      - name: Build package
        run: |
          uv build
